"""Front C audit: the constrained jet of the Lorentzian eliminated block 1 - P(s).

Bias-independent, exact verification (exact rational / symbolic arithmetic, no floating-point sampling)
of the structural form of the eliminated projector jet

    1 - P(s) = Q0 + s Q1 + s^2 Q2 + O(s^3),

before any explicit construction of E_Pi and without importing the split value |u|. The audit
guardrail it serves lives in fermionic-matter/lorentzian-eliminated-block-audit.md.

It establishes three facts.

A. Projector jet (Grassmann tangent). For a self-adjoint projector family generated by conjugation
   R(s) = U(s) Q0 U(s)^dagger with U = exp(s A), A^dagger = -A, the order-by-order constraints of
   R^2 = R force
       Q1 = [A, Q0]               (purely off-diagonal w.r.t. Q0:  Q0 Q1 Q0 = 0 = (1-Q0) Q1 (1-Q0)),
       Q2 = (1/2)[A, [A, Q0]]     with diagonal blocks fixed:  Q0 Q2 Q0 = - Q0 Q1^2 Q0.
   Imposing the J_Pi grading (Q0 even, Q1 odd) means A is J_Pi-odd: the first-order deformation of the
   eliminated subspace is a chiral (J_Pi-odd) Grassmann rotation -- the only freedom that can source
   the split. Verified on independent generic rational instances (exact arithmetic).

B. Parity propagation. Since E_Pi = -Pi_S D (1-P) D Pi_S^* is conjugation by the J_Pi-even pair
   (Pi_S, D), each E_k = -Pi_S D Q_k D Pi_S^* inherits the J_Pi-parity of Q_k: E0 even, E1 odd, E2 even.
   Verified as a symbolic operator identity.

C. Source mechanism on C^3_gen. The J_Pi-odd part of E_Pi^2 at first order in s is the anticommutator
   {E0, E1}; its J_3 component is the split source u, its R_mix component the mixing v. With phase-free
   (real) jet data the odd part lands purely on J_3 (u != 0 possible, v = 0 automatically); a nonzero
   R_mix coefficient v requires a complex metaplectic phase in E1. This matches PRS (mu == 0) and the
   FM-Note remark that generation mixing requires the complex metaplectic phase.

Convention contract for C^3_gen is frozen to ../spectral/schur_transversality_alpha.py:
    basis (e_0, e_+, e_-),  J_3 = diag(0, 1, -1),  R_mix = [[0,0,0],[0,0,1],[0,-1,0]],
    J_Pi^(2): e_0 -> -e_0, e_+ <-> e_-.

No figures. Code and comments in English.
"""

import sympy as sp


def comm(A, B):
    return A * B - B * A


def anticomm(A, B):
    return A * B + B * A


def is_zero(M):
    return sp.expand(sp.Matrix(M)) == sp.zeros(*M.shape)


def rank1_proj(v):
    """Exact real rank-1 orthogonal projector v v^T / (v^T v)."""
    v = sp.Matrix(v)
    return (v * v.T) / (v.T * v)[0]


def block4(P_plus, P_minus):
    """Embed two 2x2 blocks into a 4x4 block-diagonal matrix."""
    M = sp.zeros(4, 4)
    M[0:2, 0:2] = P_plus
    M[2:4, 2:4] = P_minus
    return M


def block_offdiag(B):
    """4x4 block off-diagonal [[0, B], [-B^T, 0]] (real anti-symmetric => anti-Hermitian, J-odd)."""
    M = sp.zeros(4, 4)
    M[0:2, 2:4] = B
    M[2:4, 0:2] = -B.T
    return M


# ---------------------------------------------------------------------------------------------------
# Part A: projector jet identities, exact rational instances, J = diag(1,1,-1,-1).
# ---------------------------------------------------------------------------------------------------
def part_A():
    J = sp.diag(1, 1, -1, -1)
    I4 = sp.eye(4)

    instances = [
        (rank1_proj([3, 4]), rank1_proj([5, 12]), sp.Matrix([[1, -2], [3, 1]])),
        (rank1_proj([2, -7]), rank1_proj([1, 1]), sp.Matrix([[4, 5], [-1, 2]])),
    ]

    checks = {}
    for idx, (Pp, Pm, B) in enumerate(instances):
        Q0 = block4(Pp, Pm)           # J-even orthogonal projector
        A = block_offdiag(B)          # J-odd anti-Hermitian generator
        Q1 = comm(A, Q0)
        Q2 = comm(A, comm(A, Q0)) / 2
        tag = f"inst{idx}"

        checks[f"{tag}.Q0_projector"] = is_zero(Q0 * Q0 - Q0)
        checks[f"{tag}.Q0_selfadjoint"] = is_zero(Q0 - Q0.T)
        checks[f"{tag}.Q0_J_even"] = is_zero(J * Q0 * J - Q0)

        checks[f"{tag}.Q1_selfadjoint"] = is_zero(Q1 - Q1.T)
        checks[f"{tag}.Q1_J_odd"] = is_zero(J * Q1 * J + Q1)
        checks[f"{tag}.Q1_offdiag_upper"] = is_zero(Q0 * Q1 * Q0)
        checks[f"{tag}.Q1_offdiag_lower"] = is_zero((I4 - Q0) * Q1 * (I4 - Q0))
        checks[f"{tag}.Q1_pure_offdiag"] = is_zero(
            Q1 - (Q0 * Q1 * (I4 - Q0) + (I4 - Q0) * Q1 * Q0)
        )
        checks[f"{tag}.Q1_nonzero"] = not is_zero(Q1)

        checks[f"{tag}.order1_constraint"] = is_zero(anticomm(Q0, Q1) - Q1)
        checks[f"{tag}.order2_constraint"] = is_zero(Q0 * Q2 + Q2 * Q0 + Q1 * Q1 - Q2)
        # Diagonal blocks of Q2 fixed by Q1^2: minus inside Q0 (eliminated subspace), plus in 1-Q0.
        checks[f"{tag}.Q2_block_upper"] = is_zero(Q0 * Q2 * Q0 + Q0 * Q1 * Q1 * Q0)
        checks[f"{tag}.Q2_block_lower"] = is_zero(
            (I4 - Q0) * Q2 * (I4 - Q0) - (I4 - Q0) * Q1 * Q1 * (I4 - Q0)
        )
        checks[f"{tag}.Q2_J_even"] = is_zero(J * Q2 * J - Q2)
    return checks


# ---------------------------------------------------------------------------------------------------
# Part A2: parity decomposition of the generator. A general A = A_+ + A_- (J-even + J-odd) gives
# Q1 = [A_+, Q0] + [A_-, Q0] with [A_+, Q0] J-even and [A_-, Q0] J-odd, so the split-sourcing part is
# Pi_{J-odd} Q1 = [A_-, Q0]. Hence the split is dead iff [A_-, Q0] = 0 (e.g. A_- with no off-diagonal
# component between Q0 and 1-Q0), NOT merely iff Q1 = 0: a purely J-even A leaves Q1 = [A_+, Q0] != 0
# while sourcing nothing.
# ---------------------------------------------------------------------------------------------------
def part_A2():
    J = sp.diag(1, 1, -1, -1)
    Q0 = block4(rank1_proj([3, 4]), rank1_proj([5, 12]))

    # J-even anti-Hermitian generator: block-diagonal real antisymmetric (commutes with J).
    x1, x2 = sp.Rational(2, 1), sp.Rational(-3, 1)
    Aplus = block4(sp.Matrix([[0, x1], [-x1, 0]]), sp.Matrix([[0, x2], [-x2, 0]]))
    # J-odd anti-Hermitian generator: block off-diagonal (anti-commutes with J).
    Aminus = block_offdiag(sp.Matrix([[1, -2], [3, 1]]))

    def odd_part(M):
        return (M - J * M * J) / 2

    checks = {}
    checks["Aplus_J_even"] = is_zero(J * Aplus * J - Aplus)
    checks["Aminus_J_odd"] = is_zero(J * Aminus * J + Aminus)

    com_plus = comm(Aplus, Q0)
    com_minus = comm(Aminus, Q0)
    checks["comm_Aplus_J_even"] = is_zero(J * com_plus * J - com_plus)
    checks["comm_Aminus_J_odd"] = is_zero(J * com_minus * J + com_minus)

    Q1 = comm(Aplus + Aminus, Q0)
    checks["odd_part_Q1_is_comm_Aminus"] = is_zero(odd_part(Q1) - com_minus)

    # Purely J-even generator: Q1 != 0 in general, but its J-odd (split-sourcing) part vanishes.
    Q1_even_only = comm(Aplus, Q0)
    checks["even_only_Q1_nonzero"] = not is_zero(Q1_even_only)
    checks["even_only_odd_part_dead"] = is_zero(odd_part(Q1_even_only))
    return checks


# ---------------------------------------------------------------------------------------------------
# Part B: parity propagation under conjugation by a J-even pair (Pi_S, D) -- symbolic operator identity.
# ---------------------------------------------------------------------------------------------------
def part_B():
    J = sp.diag(1, 1, -1, -1)
    g = sp.symbols("g0:16", real=True)
    G = sp.Matrix(4, 4, g)
    G = (G + J * G * J) / 2  # force G J-even
    q = sp.symbols("q0:16", real=True)
    Qg = sp.Matrix(4, 4, q)
    checks = {}
    for name, eps in (("even", 1), ("odd", -1)):
        Qe = (Qg + eps * J * Qg * J) / 2
        E = G * Qe * G.T
        checks[f"propagate_{name}"] = is_zero(J * E * J - eps * E)
    return checks


# ---------------------------------------------------------------------------------------------------
# Part C: source mechanism on C^3_gen (frozen convention) -- symbolic.
# ---------------------------------------------------------------------------------------------------
def hs(A, B):
    return sp.trace(A.conjugate().T * B)


def part_C():
    J = sp.Matrix([[-1, 0, 0], [0, 0, 1], [0, 1, 0]])
    J3 = sp.diag(0, 1, -1)
    Rmix = sp.Matrix([[0, 0, 0], [0, 0, 1], [0, -1, 0]])
    checks = {}

    sS = sp.symbols("S0:9", real=True)
    sT = sp.symbols("T0:9", real=True)
    S = sp.Matrix(3, 3, sS)
    S = (S + S.T) / 2
    T = sp.Matrix(3, 3, sT)
    T = (T + T.T) / 2
    E0 = (S + J * S * J) / 2          # J-even Hermitian
    E1 = (T - J * T * J) / 2          # J-odd  Hermitian

    odd1 = anticomm(E0, E1)           # first-order J_Pi-odd part of E_Pi^2
    checks["anticomm_is_J_odd"] = is_zero(J * odd1 * J + odd1)

    u1 = sp.expand(hs(odd1, J3) / hs(J3, J3))
    v1 = sp.expand(hs(odd1, Rmix) / hs(Rmix, Rmix))
    checks["v_vanishes_phase_free"] = (v1 == 0)
    checks["u_generically_nonzero"] = (u1 != 0)

    # Concrete witness with generic rational data: u != 0 with v = 0, amplitude |u| left free.
    subs = {sS[i]: val for i, val in enumerate([2, 3, 5, 7, 11, 13, 17, 19, 23])}
    subs.update({sT[i]: val for i, val in enumerate([1, 4, 9, 16, 25, 36, 49, 64, 81])})
    u_w = sp.nsimplify(u1.subs(subs))
    v_w = sp.nsimplify(v1.subs(subs))
    checks["witness_u_nonzero"] = (u_w != 0)
    checks["witness_v_zero"] = (v_w == 0)

    # Mixing requires a complex metaplectic phase: i*R_mix is Hermitian and J-odd and populates R_mix.
    a = sp.symbols("a", real=True)
    E1c = E1 + sp.I * a * Rmix
    odd1c = anticomm(E0, E1c)
    v1c = sp.expand(hs(odd1c, Rmix) / hs(Rmix, Rmix))
    checks["mixing_needs_phase"] = (sp.expand(v1c - v1).has(a))

    extras = {"u1": u1, "v1": v1, "u_witness": u_w, "v_witness": v_w}
    return checks, extras


def main():
    all_checks = {}
    all_checks.update({f"A.{k}": v for k, v in part_A().items()})
    all_checks.update({f"A2.{k}": v for k, v in part_A2().items()})
    all_checks.update({f"B.{k}": v for k, v in part_B().items()})
    cC, extras = part_C()
    all_checks.update({f"C.{k}": v for k, v in cC.items()})

    for name, ok in all_checks.items():
        print(f"  [{'OK ' if ok else 'FAIL'}] {name}")
        assert ok, name

    print()
    print("C source coefficients (generic phase-free jet):")
    print("  u1 (J_3 source)   =", extras["u1"])
    print("  v1 (R_mix mixing) =", extras["v1"], "  (identically zero without a complex phase)")
    print("  witness: u =", extras["u_witness"], ", v =", extras["v_witness"],
          "  (u != 0 with no R_mix leakage, |u| left free)")
    print()
    print("ALL EXACT CHECKS PASSED")


if __name__ == "__main__":
    main()
